name: Extract Release Type
description: Tralala

outputs:
  RELEASE_TYPE:
    description: "Release type"
    value: ${{steps.extraction.outputs.RELEASE_TYPE}}
runs:
    using: "composite" 
    steps:
      - name: Extract Release Type
        id: extraction
        shell: bash
        run: |
          # Get the commit SHA for the last merge commit
          LAST_MERGE_COMMIT_SHA=$(git log --merges -1 --format="%H")
          # Extract the merge message from the commit
          MERGE_MESSAGE=$(git log --format=%B -n 1 $LAST_MERGE_COMMIT_SHA)
          # Use regular expressions to extract the release type
          RELEASE_TYPE=$(echo "$MERGE_MESSAGE" | grep -oi 'Release type: \(\w*\)' | sed -e 's/[Rr]elease type:[[:space:]]*//' | tr -d '[:space:]')
          echo "Release Type: $RELEASE_TYPE"
          # Set the release type as an environment variable
          echo "RELEASE_TYPE=$RELEASE_TYPE" >> $GITHUB_OUTPUT


