name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  prompt-user-input:
    runs-on: ubuntu-latest

    steps:
      - name: Prompt User Input
        id: prompt
        run: |
          echo "##[set-output name=user_choice;isString=true]$(read -p 'Choose an option (A/B): ' choice && echo $choice)"
        shell: bash

      - name: Display User's Choice
        run: echo "User's choice is ${{ steps.prompt.outputs.user_choice }}"
