name: Extract Release Type

on:
  pull_request:
    types:
      - closed

jobs:
  extract-release-type:
    runs-on: ubuntu-latest
    if: ${{github.event.pull_request.merged == true}}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Extract Release Type
        run: |
          # Get the commit SHA for the last merge commit
          LAST_MERGE_COMMIT_SHA=$(git log --merges -1 --format="%H")
          # Extract the merge message from the commit
          MERGE_MESSAGE=$(git log --format=%B -n 1 $LAST_MERGE_COMMIT_SHA)
          # Use regular expressions to extract the release type
          RELEASE_TYPE=$(echo "$MERGE_MESSAGE" | grep -o 'Release type: \(\w*\)' | sed 's/Release type: //')
          echo "Release Type: $RELEASE_TYPE"
          # Set the release type as an environment variable
          echo "RELEASE_TYPE=$RELEASE_TYPE" >> $GITHUB_ENV

      - name: Echo Release Type
        run: |
          # Access the release type from the environment variable
          RELEASE_TYPE=$RELEASE_TYPE
          # Echo the release type
          echo "Extracted Release Type: $RELEASE_TYPE"
