name: Auto-increment Version Tag

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release Type'
        type: choice
        required: true
        default: 'config'
        options: 
          - 'major'
          - 'minor'
          - 'patch'
          - 'config'

jobs:
  bump_version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get current tag
      id: get_current_tag
      run: |
        release="${GITHUB_REF#refs/heads/release/}"
        latest_version=$(git tag -l | sort -V | tail -1) || echo $?
        echo "Latest version: ${latest_version}"
      
   

