name: Auto-increment Version Tag

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release Type'
        type: choice
        required: true
        default: 'config'
        options: 
          - 'major'
          - 'minor'
          - 'patch'
          - 'config'

jobs:
  bump_version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get Latest Version
      id: latest_version
      run: |
        release="${GITHUB_REF#refs/heads/release/}"
        git fetch --tags  # Fetch all tags from the remote repository
        latest_version=$(git tag --list --sort=-v:refname | head -n 1)
        echo "Latest version: $latest_version"
      continue-on-error: true

    - name: Determine New Version
      id: determine_version
      run: |
        release_type="${{ github.event.inputs.release_type }}"
        latest_version="${latest_version}"

        # Split the latest version into its components
        version_parts=()
        while IFS= read -r -d ' ' item; do
          version_parts+=("$item")
        done << (echo $latest_version | tr '.' ' ')
        echo "Array: ${version_parts}"
        major="${version_parts[0]}"
        echo "${major}"
        minor="${version_parts[1]}"
        patch="${version_parts[2]}"
        config="${version_parts[3]}"

        # Convert component strings to integers
        major=$((major))
        minor=$((minor))
        patch=$((patch))
        config=$((config))

        echo "major = ${major}"
        echo "minor = ${minor}"
        echo "patch = ${patch}"
        echo "config = ${config}"
        

    
      continue-on-error: true





