name: Auto-increment Version Tag

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release Type'
        type: choice
        required: true
        default: 'config'
        options: 
          - 'major'
          - 'minor'
          - 'patch'
          - 'config'

jobs:
  bump_version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get Latest Version
      id: latest_version
      run: |
        git tag -l 
      continue-on-error: true
    
      
   

