name: Auto-increment Version Tag

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release Type'
        type: choice
        required: true
        default: 'config'
        options: 
          - 'major'
          - 'minor'
          - 'patch'
          - 'config'

jobs:
  bump_version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get current tag
      id: get_current_tag
      run: |
        tag_name=$(git describe --tags --abbrev=0)
        echo "TAG_NAME=$tag_name" >> $GITHUB_ENV
      
   

