name: Auto-increment Version Tag

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release Type'
        type: choice
        required: true
        default: 'config'
        options: 
          - 'major'
          - 'minor'
          - 'patch'
          - 'config'

jobs:
  bump_version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get Latest Version
      id: latest_version
      run: |
        release="${GITHUB_REF#refs/heads/release/}"
        git fetch --tags  # Fetch all tags from the remote repository
        latest_version=$(git tag --list --sort=-v:refname | head -n 1)
        echo "Latest version: $latest_version"
        echo "::set-output name=latest_version::$latest_version"
      continue-on-error: true

    
      
   

